int _ABVAR_3_20;
int _ABVAR_2_9;
int _ABVAR_1_8;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  int duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(5);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  return duration;
}


void setup()
{
_ABVAR_2_9 = 9;
pinMode( 13 , OUTPUT);
_ABVAR_1_8 = 8;
_ABVAR_3_20 = 0;
digitalWrite( _ABVAR_1_8 , LOW );

}

void loop()
{
if (( ( ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( _ABVAR_1_8 , _ABVAR_2_9 ) ) >= ( _ABVAR_3_20 ) ))
{
digitalWrite( 13 , HIGH );
delay( 1000 );
}
else
{
digitalWrite( 13 , LOW );
delay( 1000 );
}
}


